Implement parsing jwt token and token calendar API
KIT-Club/kit-manager pull request #24
Opened 2023-04-23 16:52 UTC by Vu-Minh-Hoa

2023-05-07 04:12 UTC, arahiko-ayami requested changes

2023-05-07 04:12 UTC, arahiko-ayami commented on service/Index.service.ts
> +  );
Next hỗ trợ xử lí uri rồi, không dùng hàm của js để xử lí nữa

2023-05-07 04:12 UTC, arahiko-ayami commented on pages/calendar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Đừng comment để tắt lint

2023-05-07 04:12 UTC, arahiko-ayami commented on pages/calendar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Đừng comment để tắt lint

2023-05-07 04:12 UTC, arahiko-ayami commented on pages/calendar/index.tsx
> +    // await tokenCalendar(tokenData);
Kiểm tra hàm và logic ở đây, xoá các comment không cần thiết

2023-05-07 04:12 UTC, arahiko-ayami commented on pages/calendar/index.tsx
> +// import { tokenCalendar } from "../../repositories/Calendar.repository";
Check lại import này có cần thiết không

2023-05-15 16:35 UTC, ngosangns commented
Mình không cần hàm decode jwt nha em, mình chỉ cần lưu và load nó là dc rồi. Em dựng mấy hàm utils là dc

2023-05-16 10:46 UTC, Vu-Minh-Hoa commented on service/Index.service.ts
> +  );
Done

2023-05-16 10:46 UTC, Vu-Minh-Hoa commented on pages/calendar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Done

2023-05-16 10:46 UTC, Vu-Minh-Hoa commented on pages/calendar/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Done

2023-05-16 10:46 UTC, Vu-Minh-Hoa commented on pages/calendar/index.tsx
> +// import { tokenCalendar } from "../../repositories/Calendar.repository";
Done

2023-05-22 14:04 UTC, ngosangns approved these changes

2023-05-22 14:04 UTC, merged